### PR TITLE
adds elm-middleware

### PR DESCRIPTION
**Pull request by stoeffel**
How do you feel about adding this? I will have to but some more work into the docs though. But the example shows how it's used.

### CODE REVIEW

**Comment by markerikson** [comment]
Looks like your IDE just wiped out all the end-of-line whitespace in that file, which is needed to get the newlines to format correctly.

I do actually have this middleware in my current bookmarks list, which I need to sweep through here soon.  I'll close the PR, but will add the lib to the page in my next round of updates.

**Comment by stoeffel** [comment]
Nice and thanks. 
Yop, I should reconfigure my global .editorconfig

**Comment by stoeffel** [comment]
Or you could add one to your project to avoid this in other pr. I can open a pr if you like.

**Comment by markerikson** [comment]
Suppose that could be useful.  I've heard of editorconfig, but haven't used it yet.

I guess `trim_trailing_whitespace = false` would be the needed value?

Basically, I figured out that I need 2 blank spaces after the titles and the links in order to get the newlines I wanted, rather than paragraphs.

**Comment by stoeffel** [comment]
>  I guess trim_trailing_whitespace = false would be the needed value?

Yop

**Comment by markerikson** [comment]
Link added in https://github.com/markerikson/redux-ecosystem-links/commit/c4cb68615d074333b62b450ae04cc8f686337a31 .

**Pull request closed without merging**
